fail-on-severity: moderate
fail-on-scopes:
  - runtime
vulnerability-check: true
license-check: false
show-openssf-scorecard: true
warn-on-openssf-scorecard-level: 5
retry-on-snapshot-warnings: true
retry-on-snapshot-warnings-timeout: 180
