version: 2

project_name: stackctl

release:
  github:
    owner: traweezy
    name: stackctl

before:
  hooks:
    - go mod tidy

builds:
  - id: stackctl
    main: .
    binary: stackctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - >-
        -s -w
        -X main.version={{ .Version }}
        -X main.gitCommit={{ .Commit }}
        -X main.buildDate={{ .Date }}

archives:
  - id: release-archive
    ids:
      - stackctl
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - CHANGELOG.md
      - SECURITY.md

checksum:
  name_template: checksums.txt

sboms:
  - id: archive-sboms
    artifacts: archive
    documents:
      - "${artifact}.spdx.json"
    disable: false

signs:
  - id: checksum-sigstore
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

changelog:
  use: github-native
