.nh
.TH "stackctl" "1" "" "stackctl" ""

.SH NAME
stackctl-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
\fBstackctl completion zsh [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the zsh shell.

.PP
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

.EX
echo "autoload -U compinit; compinit" >> ~/.zshrc
.EE

.PP
To load completions in your current shell session:

.EX
source <(stackctl completion zsh)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
stackctl completion zsh > "${fpath[1]}/_stackctl"
.EE

.SS macOS:
.EX
stackctl completion zsh > $(brew --prefix)/share/zsh/site-functions/_stackctl
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--accessible\fP[=false]
	Render interactive prompts and spinners in accessible mode

.PP
\fB--log-file\fP=""
	Write internal logs to this path ('-' writes to stderr)

.PP
\fB--log-format\fP=""
	Set the internal log format for --log-file (text, json, logfmt)

.PP
\fB--log-level\fP=""
	Set the internal log level when --log-file is enabled

.PP
\fB--plain\fP[=false]
	Force the legacy plain-text config wizard instead of the form UI

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential progress output

.PP
\fB--stack\fP=""
	Select a named stack config (overrides STACKCTL_STACK and the saved current stack)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Print extra lifecycle detail


.SH SEE ALSO
\fBstackctl-completion(1)\fP
