.nh
.TH "stackctl" "1" "" "stackctl" ""

.SH NAME
stackctl-start - Start the local development stack or selected services


.SH SYNOPSIS
\fBstackctl start [service...] [flags]\fP


.SH DESCRIPTION
Start the local development stack or selected services


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for start


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--accessible\fP[=false]
	Render interactive prompts and spinners in accessible mode

.PP
\fB--log-file\fP=""
	Write internal logs to this path ('-' writes to stderr)

.PP
\fB--log-format\fP=""
	Set the internal log format for --log-file (text, json, logfmt)

.PP
\fB--log-level\fP=""
	Set the internal log level when --log-file is enabled

.PP
\fB--plain\fP[=false]
	Force the legacy plain-text config wizard instead of the form UI

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential progress output

.PP
\fB--stack\fP=""
	Select a named stack config (overrides STACKCTL_STACK and the saved current stack)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Print extra lifecycle detail


.SH EXAMPLE
.EX
  stackctl start
  stackctl start postgres
  stackctl start redis nats
.EE


.SH SEE ALSO
\fBstackctl(1)\fP
