.nh
.TH "stackctl" "1" "" "stackctl" ""

.SH NAME
stackctl-stack - Manage named stack profiles


.SH SYNOPSIS
\fBstackctl stack [flags]\fP


.SH DESCRIPTION
Manage named stack profiles


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stack


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--accessible\fP[=false]
	Render interactive prompts and spinners in accessible mode

.PP
\fB--log-file\fP=""
	Write internal logs to this path ('-' writes to stderr)

.PP
\fB--log-format\fP=""
	Set the internal log format for --log-file (text, json, logfmt)

.PP
\fB--log-level\fP=""
	Set the internal log level when --log-file is enabled

.PP
\fB--plain\fP[=false]
	Force the legacy plain-text config wizard instead of the form UI

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential progress output

.PP
\fB--stack\fP=""
	Select a named stack config (overrides STACKCTL_STACK and the saved current stack)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Print extra lifecycle detail


.SH EXAMPLE
.EX
  stackctl stack list
  stackctl stack current
  stackctl stack use staging
  stackctl stack clone dev-stack demo
  stackctl stack rename demo qa
  stackctl stack delete qa --purge-data --force
.EE


.SH SEE ALSO
\fBstackctl(1)\fP, \fBstackctl-stack-clone(1)\fP, \fBstackctl-stack-current(1)\fP, \fBstackctl-stack-delete(1)\fP, \fBstackctl-stack-list(1)\fP, \fBstackctl-stack-rename(1)\fP, \fBstackctl-stack-use(1)\fP
