package main

import (
	"bytes"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

const testGenerateMainModeEnv = "STACKCTL_TEST_GENERATE_MAIN_MODE"

func TestDisableAutoGenTagsRecurses(t *testing.T) {
	root := &cobra.Command{Use: "root"}
	child := &cobra.Command{Use: "child"}
	grandchild := &cobra.Command{Use: "grandchild"}
	child.AddCommand(grandchild)
	root.AddCommand(child)

	disableAutoGenTags(root)

	for _, cmd := range []*cobra.Command{root, child, grandchild} {
		if !cmd.DisableAutoGenTag {
			t.Fatalf("expected %q to disable autogenerated tags", cmd.Name())
		}
	}
}

func TestRecreateDirRemovesExistingContents(t *testing.T) {
	root := openTempRoot(t)

	if err := root.MkdirAll(filepath.Join(markdownDir, "nested"), 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := root.WriteFile(filepath.Join(markdownDir, "nested", "old.txt"), []byte("stale"), 0o600); err != nil {
		t.Fatalf("write stale file: %v", err)
	}

	if err := recreateDir(root, markdownDir); err != nil {
		t.Fatalf("recreate dir: %v", err)
	}

	entries, err := os.ReadDir(filepath.Join(root.Name(), markdownDir))
	if err != nil {
		t.Fatalf("read recreated dir: %v", err)
	}
	if len(entries) != 0 {
		t.Fatalf("expected recreated dir to be empty, got %d entries", len(entries))
	}
}

func TestRecreateDirReturnsErrorWhenParentIsFile(t *testing.T) {
	root := openTempRoot(t)

	if err := root.WriteFile("docs", []byte("blocking file"), 0o600); err != nil {
		t.Fatalf("write blocking file: %v", err)
	}

	if err := recreateDir(root, markdownDir); err == nil {
		t.Fatal("expected recreateDir to fail when a parent path is a file")
	}
}

func TestWriteCompletionFileWritesContent(t *testing.T) {
	root := openTempRoot(t)

	if err := root.MkdirAll(completionsDir, 0o750); err != nil {
		t.Fatalf("mkdir completions: %v", err)
	}

	target := filepath.Join(completionsDir, "stackctl.test")
	if err := writeCompletionFile(root, target, func(w io.Writer) error {
		_, err := io.WriteString(w, "completion output")
		return err
	}); err != nil {
		t.Fatalf("write completion file: %v", err)
	}

	content, err := root.ReadFile(target)
	if err != nil {
		t.Fatalf("read completion file: %v", err)
	}
	if string(content) != "completion output" {
		t.Fatalf("unexpected completion content: %q", string(content))
	}
}

func TestWriteCompletionFileClosesFileOnGeneratorError(t *testing.T) {
	root := openTempRoot(t)

	if err := root.MkdirAll(completionsDir, 0o750); err != nil {
		t.Fatalf("mkdir completions: %v", err)
	}

	target := filepath.Join(completionsDir, "stackctl.test")
	expectedErr := errors.New("boom")
	err := writeCompletionFile(root, target, func(io.Writer) error {
		return expectedErr
	})
	if !errors.Is(err, expectedErr) {
		t.Fatalf("expected %v, got %v", expectedErr, err)
	}
}

func TestWriteCompletionFileReturnsOpenErrorWhenParentIsMissing(t *testing.T) {
	root := openTempRoot(t)

	target := filepath.Join(completionsDir, "stackctl.test")
	if err := writeCompletionFile(root, target, func(io.Writer) error { return nil }); err == nil {
		t.Fatal("expected completion file creation to fail without a parent directory")
	}
}

func TestNormalizeManDatesClearsTHDate(t *testing.T) {
	root := openTempRoot(t)

	if err := root.MkdirAll(manDir, 0o750); err != nil {
		t.Fatalf("mkdir man dir: %v", err)
	}

	path := filepath.Join(manDir, "stackctl.1")
	content := ".TH \"stackctl\" \"1\" \"Apr 2026\" \"stackctl\" \"stackctl\"\n.SH NAME\nstackctl\n"
	if err := root.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write man page: %v", err)
	}

	if err := normalizeManDates(root, manDir); err != nil {
		t.Fatalf("normalize man dates: %v", err)
	}

	normalized, err := root.ReadFile(path)
	if err != nil {
		t.Fatalf("read normalized man page: %v", err)
	}
	if !strings.Contains(string(normalized), ".TH \"stackctl\" \"1\" \"\" \"stackctl\" \"stackctl\"") {
		t.Fatalf("expected normalized .TH date field:\n%s", string(normalized))
	}
}

func TestNormalizeManDatesReturnsWalkErrorForMissingPath(t *testing.T) {
	root := openTempRoot(t)

	if err := normalizeManDates(root, manDir); err == nil {
		t.Fatal("expected normalizeManDates to fail when the man directory is missing")
	}
}

func TestGenerateCLIAssetsCreatesDocsManAndCompletions(t *testing.T) {
	originalWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	tempDir := t.TempDir()
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("chdir temp dir: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	if err := generateCLIAssets(); err != nil {
		t.Fatalf("generate cli assets: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(markdownDir, "stackctl.md"),
		filepath.Join(markdownDir, "stackctl_tui.md"),
		filepath.Join(manDir, "stackctl.1"),
		filepath.Join(completionsDir, "stackctl.bash"),
		filepath.Join(completionsDir, "_stackctl"),
		filepath.Join(completionsDir, "stackctl.fish"),
		filepath.Join(completionsDir, "stackctl.ps1"),
	}

	for _, path := range expectedFiles {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected generated asset %s: %v", path, err)
		}
	}
}

func TestGenerateCLIAssetsReturnsErrorWhenDocsParentIsFile(t *testing.T) {
	originalWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	tempDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(tempDir, "docs"), []byte("blocking file"), 0o600); err != nil {
		t.Fatalf("write blocking file: %v", err)
	}
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("chdir temp dir: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(originalWD)
	})

	if err := generateCLIAssets(); err == nil {
		t.Fatal("expected generateCLIAssets to fail when docs is a file")
	}
}

func TestMainGeneratesCLIAssetsFromCurrentDirectory(t *testing.T) {
	tempDir := t.TempDir()
	cmd := exec.Command(os.Args[0], "-test.run=TestGenerateCLIAssetsMainHelper")
	cmd.Dir = tempDir
	cmd.Env = append(os.Environ(), testGenerateMainModeEnv+"=success")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		t.Fatalf("run generator main helper: %v", err)
	}
	if stdout.Len() != 0 {
		t.Fatalf("expected no stdout output, got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("expected no stderr output, got %q", stderr.String())
	}

	expectedFiles := []string{
		filepath.Join(tempDir, markdownDir, "stackctl.md"),
		filepath.Join(tempDir, manDir, "stackctl.1"),
		filepath.Join(tempDir, completionsDir, "stackctl.bash"),
	}

	for _, path := range expectedFiles {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected generated asset %s: %v", path, err)
		}
	}
}

func TestMainPrintsErrorAndExitsNonZeroWhenGenerationFails(t *testing.T) {
	tempDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(tempDir, "docs"), []byte("blocking file"), 0o600); err != nil {
		t.Fatalf("write blocking file: %v", err)
	}

	cmd := exec.Command(os.Args[0], "-test.run=TestGenerateCLIAssetsMainHelper")
	cmd.Dir = tempDir
	cmd.Env = append(os.Environ(), testGenerateMainModeEnv+"=failure")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("expected exit error, got %v", err)
	}
	if exitErr.ExitCode() != 1 {
		t.Fatalf("expected exit code 1, got %d", exitErr.ExitCode())
	}
	if stdout.Len() != 0 {
		t.Fatalf("expected no stdout output, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "generate CLI assets:") {
		t.Fatalf("expected stderr to include generation failure, got %q", stderr.String())
	}
}

func TestGenerateCLIAssetsMainHelper(t *testing.T) {
	mode := os.Getenv(testGenerateMainModeEnv)
	if mode == "" {
		return
	}
	if mode == "failure" {
		if err := os.WriteFile("docs", []byte("blocking file"), 0o600); err != nil {
			t.Fatalf("write blocking file: %v", err)
		}
	}

	main()
	os.Exit(0)
}

func openTempRoot(t *testing.T) *os.Root {
	t.Helper()

	root, err := os.OpenRoot(t.TempDir())
	if err != nil {
		t.Fatalf("open root: %v", err)
	}
	t.Cleanup(func() {
		_ = root.Close()
	})
	return root
}
